### ISSUE TITLE
Crypto error when installing

### ISSUE THREAD

**Issue by nedludd** [jaksi/sshesame#1]
I'm getting this.  Can't find much on the googs about it.

```
% go get -u github.com/jaksi/sshesame
# golang.org/x/crypto/ed25519
src/golang.org/x/crypto/ed25519/ed25519.go:54: undefined: crypto.SignerOpts
```

**Comment by Petros99** [comment]
You might be using an old version of go. The version on Debian stable is
too old, try going to the testing distribution.

**Comment by nedludd** [comment]
D'oh, you're right, Ubuntu way behind.  Default is 1.2. Sorry for the bother.
