### ISSUE TITLE
Add support to seperate source IP and port

### ISSUE THREAD

**Issue by Asleep-at-the-wheel** [jaksi/sshesame#105]
Are we able to add and option for separating the source IP and port in the json logs?

Example:
`{"time":"2022-06-07T06:43:19Z","source":"10.10.10.10:45888","event_type":"connection_close","event":{}}`
Becomes:
`{"time":"2022-06-07T06:43:19Z","source":"10.10.10.10","source-port":"45888","event_type":"connection_close","event":{}}`

Or something along those lines?

This will assist greatly with compatibility in other packages that just require just an IP.

**Comment by jaksi** [comment]
Thanks for the feature request! Sounds useful indeed.
Added a [`logging.split_host_port`](https://github.com/jaksi/sshesame/blob/master/sshesame.yaml#L36-L37) config option in https://github.com/jaksi/sshesame/pull/106 (v0.0.25) for this.
Enabling it (and [`logging.json`](https://github.com/jaksi/sshesame/blob/master/sshesame.yaml#L23-L24)) should make your example log line look something like  `{"time":"2022-06-07T06:43:19Z","source":{"host":"10.10.10.10","port":45888},"event_type":"connection_close","event":{}}`.

**Comment by Asleep-at-the-wheel** [comment]
> Thanks for the feature request! Sounds useful indeed. Added a [`logging.split_host_port`](https://github.com/jaksi/sshesame/blob/master/sshesame.yaml#L36-L37) config option in #106 (v0.0.25) for this. Enabling it (and [`logging.json`](https://github.com/jaksi/sshesame/blob/master/sshesame.yaml#L23-L24)) should make your example log line look something like `{"time":"2022-06-07T06:43:19Z","source":{"host":"10.10.10.10","port":45888},"event_type":"connection_close","event":{}}`.

Great! I use it as a container and feed the JSON logs directly into elasticsearch. Being able to easily separate the IP and port will really help with a bunch of other stuff that I do from there.

Thanks again!
