### ISSUE TITLE
Lacks documenation and configuration ability

### ISSUE THREAD

**Issue by Auguss82** [jaksi/sshesame#12]
Documentation does not explicitly state where logs are kept or written
No option in the configuration file to change the log location
No option to for logtypes as if i just want plain lined text and find JSON unneeded
Documentation is also very vague on setting the configuration file change the listen_address. I had to rummage through the program and systemctl to determine that I need to add listen_address to the configuration file for it to allow remote hosts.

**Comment by jaksi** [comment]
Sorry for the late reply and thank you for the feedback!
I did a rewrite of the project so these should be fixed / much better now.

>Documentation does not explicitly state where logs are kept or written

Added a [sample config file](https://github.com/jaksi/sshesame/blob/master/sshesame.yaml#L2) with comments and a note about logging in [the Configuration section of the README](https://github.com/jaksi/sshesame/blob/master/README.md#configuration)

>No option in the configuration file to change the log location

Added a [`logfile` config option](https://github.com/jaksi/sshesame/blob/master/sshesame.yaml#L2).

>No option to for logtypes as if i just want plain lined text and find JSON unneeded

Added a [`jsonlogging` config option](https://github.com/jaksi/sshesame/blob/master/sshesame.yaml#L3).

>Documentation is also very vague on setting the configuration file change the listen_address. I had to rummage through the program and systemctl to determine that I need to add listen_address to the configuration file for it to allow remote hosts.

Same as the first point, the [sample config](https://github.com/jaksi/sshesame/blob/master/sshesame.yaml#L1), linked from the [README](https://github.com/jaksi/sshesame/blob/master/README.md#configuration), now has all the config options listed, including `listenaddress`. This specific option does not have a comment but I think it should be pretty self-explanatory.
