### ISSUE TITLE
listen_address it is not a valid snap option name

### ISSUE THREAD

**Issue by dieterstueken** [jaksi/sshesame#13]
Using snap does not work well with `listen_address` since it is not a [valid snap option](https://bugs.launchpad.net/snapd/+bug/1689396) name.
Please use an appropriate option name to feed the `--listen_address` argument.

**Comment by jaksi** [comment]
The project has been rewritten since the `snap` package was created / updated.
Unfortunately I do not control the snap package and have ~0 experience with snap in general. I will contact the maintainer and ask them to transfer the ownership and will look into this.

**Comment by jaksi** [comment]
I managed to take ownership of the snap package and added [some automation](https://github.com/jaksi/sshesame/blob/master/.github/workflows/release.yml#L96-L107) for automatic Snap releases. The [sshesame snap package](https://snapcraft.io/sshesame) should be up to date now.
