### ISSUE TITLE
Failed to read host key

### ISSUE THREAD

**Issue by JonKensy** [jaksi/sshesame#2]
Hi - installed go and got the sshesame from github but I get a "failed to read host key" error when I run sshesame

**Comment by bomiga** [comment]
The readme.MD mentions that you have to specify "a file containing a private key to use (default "host_key")". This being said I just used an online generator like this here(http://travistidwell.com/blog/2013/09/06/an-online-rsa-public-and-private-key-generator/) and saved the private key as a file.pam and managed to start sshesame with the command `./sshesame -host_key host_key.pam`

**Comment by jaksi** [comment]
You need a private key to use sshesame. You can use `ssh-keygen` to generate one.
For example:
```Shell
ssh-keygen -N '' -f host_key
```
