### ISSUE TITLE
sshesame doesn't generate a host key

### ISSUE THREAD

**Issue by chadmiller** [jaksi/sshesame#3]
The host_key part is an opaque mystery, which is fine if sshsame can generate its own key file.

**Comment by jaksi** [comment]
sshesame, just like OpenSSH, uses standard PEM private keys. I don't think it should be sshesame's task to generate one.
It should however be better documented, I agree on that.
Also, it could generate a temporary in-memory private key on startup if no private key was specified (with a warning message).

Anyway, I'll try to implement some solution to this later tomorrow.
