### ISSUE TITLE
release as snap packages?

### ISSUE THREAD

**Issue by chadmiller** [jaksi/sshesame#4]
I made the two files that transform this into a Snap package. You can take over releasing packages into the several distros that support Snap packages, do nothing, or give me permission to distribute packages with the name "sshesame". It's pretty easy to manage these yourself, and not rely on others to get sshesame into distros. I think you should do that. Maybe include these two files in your repo too.

http://bazaar.launchpad.net/~cmiller/+junk/sshesame-snap/files

http://snapcraft.io/

https://myapps.developer.ubuntu.com/

(The second file, implementing configuration of the port and listen address, won't be supported in released "snapcraft" until next week.)

I uploaded a candidate with my name in it. You can try on Ubuntu 16.04, for instance, with 

`sudo apt install snapd; sudo snap install sshesame-cmiller --candidate`

and maybe

`sudo snap set sshesame-cmiller port=2203 listen_address=42.42.42.42`

Your packages won't have "-cmiller" on it.

You're awesome. Thanks for writing sshesame.

**Comment by jaksi** [comment]
I'm not familiar with Snap and I won't have time in the near future to work with it. Also, I don't think package manager specific configurations should be kept in the upstream repository.

That being said, I've tested your package and it works great, thank you for doing it!

One thing though, no SSH key is generated in the package, resulting in a new key being used after each restart. Changing the private key for an SSH server seems like a bad idea, even for a honeypot like this. I think a key should be generated when installing and used with `-host_key`, if possible.

Also, feel free to use sshesame as the name of the package.

**Comment by chadmiller** [comment]
There's nothing left to do, and I thought perhaps a branch would be a good place, but I'm not insisting. I'll trigger a re-build and upload every so often.

If you find and fix a grave security bug, then please let me know.

**Comment by chadmiller** [comment]
Also, I'm unpublishing sshesame-cmiller and publishing as sshesame. Your current snap won't get updates.
