### ISSUE TITLE
not connecting

### ISSUE THREAD

**Issue by cfpwastaken** [jaksi/sshesame#43]
Every time I enter a username and password nothing happens and it gets stuck.
SSH Client:
`login as: cfp
cfp@localhost's password:(me entering some random bullshit here)`

SSH Fakeserver:
`2021/06/30 16:27:00 No host keys configured, using keys at C:\Users\chaos\AppData\Local/sshesame
2021/06/30 16:27:00 Listening on 127.0.0.1:2022
time="2021-06-30T16:27:09+02:00" level=info msg="Connection accepted" remote_address="127.0.0.1:2035"
time="2021-06-30T16:27:10+02:00" level=info msg="Client attempted to authenticate" client_version=SSH-2.0-PuTTY_Release_0.73 method=none remote_address="127.0.0.1:2035" session_id=BgDT5oUqAqtuMuc6B/YGnjIQ9JRXGEEG/2GkI5sSV8g success=false user=cfp
time="2021-06-30T16:27:12+02:00" level=info msg="Password authentication attempted" client_version=SSH-2.0-PuTTY_Release_0.73 password=cfp remote_address="127.0.0.1:2035" session_id=BgDT5oUqAqtuMuc6B/YGnjIQ9JRXGEEG/2GkI5sSV8g success=true user=cfp
time="2021-06-30T16:27:12+02:00" level=info msg="Client attempted to authenticate" client_version=SSH-2.0-PuTTY_Release_0.73 method=password remote_address="127.0.0.1:2035" session_id=BgDT5oUqAqtuMuc6B/YGnjIQ9JRXGEEG/2GkI5sSV8g success=true user=cfp
time="2021-06-30T16:27:12+02:00" level=info msg="SSH connection established" client_version=SSH-2.0-PuTTY_Release_0.73 remote_address="127.0.0.1:2035" session_id=BgDT5oUqAqtuMuc6B/YGnjIQ9JRXGEEG/2GkI5sSV8g user=cfp
time="2021-06-30T16:27:12+02:00" level=info msg="New channel accepted" channel_id=1 channel_type=session client_version=SSH-2.0-PuTTY_Release_0.73 remote_address="127.0.0.1:2035" session_id=BgDT5oUqAqtuMuc6B/YGnjIQ9JRXGEEG/2GkI5sSV8g user=cfp
time="2021-06-30T16:27:12+02:00" level=info msg="Channel request accepted" channel_id=1 channel_type=session client_version=SSH-2.0-PuTTY_Release_0.73 remote_address="127.0.0.1:2035" request_payload="Term: xterm, Size: 80x24 (0x0 px), Modes: VERASE=127, OPCODE_42=1, TTY_OP_ISPEED=38400, TTY_OP_OSPEED=38400" request_type=pty-req request_want_reply=true session_id=BgDT5oUqAqtuMuc6B/YGnjIQ9JRXGEEG/2GkI5sSV8g user=cfp
time="2021-06-30T16:27:12+02:00" level=info msg="Channel request accepted" channel_id=1 channel_type=session client_version=SSH-2.0-PuTTY_Release_0.73 remote_address="127.0.0.1:2035" request_payload= request_type=shell request_want_reply=true session_id=BgDT5oUqAqtuMuc6B/YGnjIQ9JRXGEEG/2GkI5sSV8g user=cfp`

Can someone help me this is confusing and there is so much log output

**Comment by jaksi** [comment]
Hi, thanks for the interest in the project and the feedback!

I have just merged https://github.com/jaksi/sshesame/pull/46 which improves session channels a lot, could you try using the latest version from master?

Also, as far as I can tell you are using PuTTY as a client which I'm not actively testing with. Based on the logs you've pasted I don't see why it should not work, but I'll test it myself in the evening (in a few hours).

As for the logs, I have to agree, I ended up including a bunch of seemingly useful / interesting stuff in the logs which made them quite difficult to read and understand. I created https://github.com/jaksi/sshesame/issues/45 to figure out how to improve this.

**Comment by cfpwastaken** [comment]
> As for the logs, I have to agree, I ended up including a bunch of seemingly useful / interesting stuff in the logs which made them quite difficult to read and understand. I created #45 to figure out how to improve this.

And Idea would be to just add a -debug parameter to show extended Infos

**Comment by cfpwastaken** [comment]
And yes it does seem to be working now.
The only problem is that every command I type in just does nothing. Is this intentional?
I would look in the sources themself but I don't really know how go works soooo

**Comment by jaksi** [comment]
Yes, no commands are implemented for now. I want to get the foundations done first and then see what commands attackers tend to use and start implementing them.

FYI terminal input is read [here](https://github.com/jaksi/sshesame/blob/8bae1baf13c48a8c1c3954181074dd3e35d7a470/session.go#L238) and logged [here](https://github.com/jaksi/sshesame/blob/8bae1baf13c48a8c1c3954181074dd3e35d7a470/session.go#L281).

**Comment by cfpwastaken** [comment]
oh ok

**Comment by jaksi** [comment]
FYI I've simplified logging in https://github.com/jaksi/sshesame/pull/49 a lot, should be much more easy to understand now.

Thanks again for the feedback!
