### ISSUE TITLE
Feature request: make the software available as a snap

### ISSUE THREAD

**Issue by zyga** [jaksi/sshesame#7]
Hey

You may be interested in using snapcraft to build snaps and offer them for download to anyone on a number of distributions. For some marketing details see http://snapcraft.io. For a simple golang example look at https://github.com/snapcore/snapcraft/blob/master/demos/gopaste/snapcraft.yaml

**Comment by jaksi** [comment]
Hi

@chadmiller already [asked about this](https://github.com/jaksi/sshesame/issues/4) and made [a package](https://code.launchpad.net/~privacy-squad/+junk/sshesame-snap), which I have now mentioned in the README.

Thanks!
