### ISSUE TITLE
field debug not found in type main.loggingConfig

### ISSUE THREAD

**Issue by chencheyu** [jaksi/sshesame#71]
struct contains the debug field, but sshdsame.conf does not.
https://github.com/jaksi/sshesame/blob/ba0ef8eb5ee387c637980ba8a2672acd2cf97ee9/config.go#L29
`ERROR 2021/08/16 15:45:43 Failed to get config: yaml: unmarshal errors:
  line 9: field debug not found in type main.loggingConfig`

**Comment by jaksi** [comment]
Thanks for reporting this!
Should be fixed with https://github.com/jaksi/sshesame/pull/73.
