### ISSUE TITLE
unmarshal error for field Language of type disconnectMsg"

### ISSUE THREAD

**Issue by erjoalgo** [jaksi/sshesame#8]
```
time="2017-10-02T00:44:46-07:00" level=warning msg="Failed to establish SSH connection:ssh: unmarshal error for field Language of type disconnectMsg"
```

**Comment by jaksi** [comment]
Sorry for the, uh, 3.5 years late reply.
This message should be the result of a client not sending an SSH protocol message properly, possibly because the connection has closed before the complete message was sent (this was part of a `disconnectMsg`).
