### ISSUE TITLE
option to let in clients before password authentication

### ISSUE THREAD

**Issue by erjoalgo** [jaksi/sshesame#9]
Many clients don't offer password authentication:

> ttime="2017-10-02T01:29:33-07:00" level=info msg="Client connected" client="8.8.8.8:55398"
> time="2017-10-02T01:29:38-07:00" level=warning msg="Failed to establish SSH connection:ssh: disconnect, reason 11: "
> time="2017-10-02T01:30:05-07:00" level=warning msg="Failed to establish SSH connection:read tcp 8.8.8.8:22->8.8.8.8:55063: read: connection reset by peer"
> time="2017-10-02T01:30:40-07:00" level=info msg="Client connected" client="8.8.8.8:51635"
> time="2017-10-02T01:30:54-07:00" level=warning msg="Failed to establish SSH connection:ssh: disconnect, reason 11: "
> time="2017-10-02T01:31:13-07:00" level=info msg="Client connected" client="8.8.8.8:41782"
> time="2017-10-02T01:31:18-07:00" level=warning msg="Failed to establish SSH connection:[no auth passed yet]"
> time="2017-10-02T01:31:36-07:00" level=info msg="Client connected" client="8.8.8.8:52254"
> time="2017-10-02T01:31:36-07:00" level=warning msg="Failed to establish SSH connection:ssh: no common algorithm for host key; client offered: [ssh-rsa ssh-dss], server offered: [ssh-ed25519]"
> time="2017-10-02T01:32:37-07:00" level=info msg="Client connected" client="8.8.8.8:51105"
> time="2017-10-02T01:32:39-07:00" level=warning msg="Failed to establish SSH connection:ssh: no common algorithm for host key; client offered: [ssh-rsa ssh-dss], server offered: [ssh-ed25519]"

**Comment by jaksi** [comment]
Apologies for the insanely late reply. This should be fixed with the recent rewrite, as you can set `noclientauth: true` in the [config file](https://github.com/jaksi/sshesame/blob/master/sshesame.yaml#L7).
